[rpc]
goerliAPI = ""
mainnetAPI = ""

[wallet]
privateKey = ""
publicKey = ""

[etherscan]
goerliAPI = ""
mainnetAPI = ""
ApiKey = ""

[mysql]
User = ""
Passwd = ""
Addr = ""
DBName = ""

[jwt]
privateKey = ""
expires = ""